---
distcc_enabled: "{{ (distcc | default({})).enabled | default(false) | bool }}"
distcc_package: sys-devel/distcc
distcc_port: "{{ (distcc | default({})).port | default(3632) }}"
distcc_jobs: "{{ (distcc | default({})).jobs | default((distcc | default({})).slots | default(ansible_facts.processor_vcpus | default(4))) }}"
distcc_nice: "{{ (distcc | default({})).nice | default(15) }}"
distcc_listen: "{{ (distcc | default({})).listen | default('0.0.0.0') }}"
distcc_default_allow: []
distcc_allow: "{{ (distcc | default({})).allow | default(distcc_default_allow) }}"
