gentoo_operating_mode: shared  # standalone: ローカルのみ, shared: NFS 等の共有リソース利用
gentoo_binpkg_base: /srv/gentoo/binpkgs
gentoo_binpkg_nfs_enabled: false
gentoo_binpkg_nfs_src: ""
gentoo_binpkg_nfs_fstype: nfs4
gentoo_binpkg_nfs_opts: vers=4.2,hard,timeo=600,retrans=2,nodev,nosuid,noatime,rsize=1048576,wsize=1048576
gentoo_binpkg_nfs_require_mounted: true
gentoo_binpkg_include_cpu_key: true
gentoo_binpkg_cpu_key: ""
gentoo_chost: aarch64-unknown-linux-gnu
gentoo_profile_name: ""
