mimir:
  structuredConfig:
    multitenancy_enabled: true
    usage_stats:
      enabled: false
    server:
      log_level: info
    blocks_storage:
      backend: s3
      s3:
        bucket_name: ""
        endpoint: ""
        access_key_id: ""
        secret_access_key: ""
        insecure: true
    ruler_storage:
      backend: s3
      s3:
        bucket_name: ""
        endpoint: ""
        access_key_id: ""
        secret_access_key: ""
        insecure: true
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: ""
        endpoint: ""
        access_key_id: ""
        secret_access_key: ""
        insecure: true
    limits:
      max_global_series_per_user: 150000
      max_global_series_per_metric: 200000
    frontend:
      log_queries_longer_than: 5m
    store_gateway:
      sharding_ring:
        replication_factor: 1

global:
  podLabels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/part-of: observability

nginx:
  enabled: false

metaMonitoring:
  dashboards:
    enabled: false
  prometheus:
    enabled: false
